# Generated by Django 2.1.3 on 2019-01-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190109_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='http://qwe', max_length=200, verbose_name='访问地址'),
        ),
    ]
